website/authors/urls.py
"""URL routing for the authors app."""
from django.urls import path, re_path

from .views import CreateArticle, DeleteArticle, UpdateArticle

app_name = "authors"
urlpatterns = [
    path('nieuw/', CreateArticle.as_view(), name="article-new"),
    re_path(r'bewerk/(?P<pk>[\d]{1,})/$', UpdateArticle.as_view(), name='article-update'),
    re_path(r'verwijder/(?P<pk>[\d]{1,})/$', DeleteArticle.as_view(), name='article-delete'),
]

website/home/urls.py
from django.urls import path, re_path

from .views import Home, News

app_name = "home"
urlpatterns = [
    path('', Home.as_view(), name='index'),
    re_path(r'nieuws/(?P<pk>[\d]{1,})-(?P<slug>[\w-]+[\w]+)/$', News.as_view(), name='article')
]

website/photos/urls.py
from django.urls import path

from .views import ArticleAddPhotos, ArticleRemovePhotos

app_name = "photos"
urlpatterns = [
    path('artikel/<int:pk>/toevoegen', ArticleAddPhotos.as_view(), name='article-add'),
    path('artikel/<int:pk>/verwijderen', ArticleRemovePhotos.as_view(), name="article-remove"),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('website.home.urls')),
    path('gebruikers/', include('website.users.urls')),
    path('berichten/', include('website.authors.urls')),
    path('profiel/', include('website.userprofile.urls')),
    path('fotos/', include('website.photos.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/userprofile/urls.py
"""URL routing for the authors app."""
from django.urls import re_path

from website.userprofile.views import EditProfile

app_name = "userprofile"
urlpatterns = [
    re_path(r'bewerk/$', EditProfile.as_view(), name='profile-edit'),
]

website/users/urls.py
from django.urls import path

from .views import ChangePassword, LoginPage, LogoutPage

app_name = "users"
urlpatterns = [
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('wachtwoord/', ChangePassword.as_view(), name="change-password")
]

website/photos/models/photos.py
"""Models for storing photos."""
from django.contrib.auth import get_user_model
from django.db import models

from website.utils import ResizedHashNameImageField


class Photo(models.Model):
    """Model that represents a single, stored photo"""

    image = ResizedHashNameImageField(
        verbose_name="Foto",
        max_width=900,
        max_height=600,
        upload_to="photos"
    )

    creator = models.ForeignKey(
        get_user_model(),
        verbose_name="Gebruiker",
        on_delete=models.PROTECT,
    )

    creation_date = models.DateTimeField(
        verbose_name="Uploaddatum",
        auto_now_add=True,
    )

website/users/models/users.py
"""Represents the default user model for the Minigigs website."""
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """The base user model."""

    def __str__(self) -> str:
        """Returns a capitalized version of the user's first name."""
        return self.first_name.capitalize()

website/authors/forms/article.py
"""Forms related to articles."""
import django.forms

from website.home.models import Article
from website.utils import ClearableImageInput


class NewArticleForm(django.forms.ModelForm):
    """Form to create a new article."""

    cover_image = django.forms.ImageField(
        required=False, widget=ClearableImageInput, label="Artikelfoto"
    )

    class Meta:
        """Meta-information for the ModelForm."""

        model = Article
        fields = ["title", "content", "cover_image"]


class UpdateArticleForm(django.forms.ModelForm):
    """Form to edit an existing article."""

    cover_image = django.forms.ImageField(
        required=False, widget=ClearableImageInput, label="Artikelfoto"
    )

    class Meta:
        """Meta-information about the ModelForm."""

        model = Article
        fields = ["title", "content", "cover_image", "pubdate"]

website/photos/forms/photos.py
import logging
from typing import Generator

from django import forms

from website.home.models import Article

log = logging.getLogger(__name__)


class MultiplePhotosForm(forms.Form):
    """A form to upload multiple photos at once."""

    photos = forms.ImageField(
        label="Foto's",
        widget=forms.ClearableFileInput(attrs={"multiple": True})
    )


class RemovePhotosFromArticleForm(forms.Form):
    """A form to remove photos from an article."""

    def __init__(self, article: Article, *args, **kwargs):
        self.instance = kwargs.pop('instance')
        super().__init__(*args, **kwargs)

        for photo in article.photos.all():
            field = forms.BooleanField(
                label=photo.image.url,
                required=False,
            )
            field.creator = photo.creator
            field.creation_date = photo.creation_date
            field.n_articles = photo.articles.all().distinct().count()
            self.fields[f"photo_{photo.pk}"] = field

    @property
    def photos_to_remove(self) -> Generator[int, None, None]:
        """Yield the photos that we want to remove from the article."""
        for name, checked in self.cleaned_data.items():
            if name.startswith("photo_") and checked:
                _, _, pk = name.partition("_")
                yield int(pk)

website/userprofile/forms/profile.py
"""Forms related to articles."""
import django.forms

from website.userprofile.models import Profile
from website.utils.form import ClearableImageInput


class EditProfileForm(django.forms.ModelForm):
    """Form to change your profile picture."""

    profile_picture = django.forms.ImageField(required=False, widget=ClearableImageInput,
                                              label="Profielfoto")

    class Meta:
        """Meta-information for the ModelForm."""

        model = Profile
        fields = ["profile_picture"]

website/users/forms/change_password.py
"""Custom login form that sets the correct widget class attributes."""
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext_lazy as _


class ChangePasswordForm(PasswordChangeForm):
    """Custom authentication form."""

    old_password = forms.CharField(
        label=_("Oud wachtwoord"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'input is-rounded'}),
    )

    new_password1 = forms.CharField(
        label=_("Nieuw wachtwoord"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'input is-rounded'}),
    )

    new_password2 = forms.CharField(
        label=_("Herhaal nieuw wachtwoord"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'input is-rounded'}),
    )

website/users/forms/login.py
"""Custom login form that sets the correct widget class attributes."""
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.utils.translation import gettext_lazy as _


class AuthForm(AuthenticationForm):
    """Custom authentication form."""

    username = UsernameField(
        widget=forms.TextInput(
            attrs={'autofocus': True, 'class': 'input is-rounded'}
        )
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'input is-rounded'}),
    )

website/authors/views/article.py
"""View that allows an authenticated user to create a new article."""
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, reverse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from website.authors.forms.article import NewArticleForm, UpdateArticleForm
from website.home.models import Article

log = logging.getLogger(__name__)


class CreateArticle(LoginRequiredMixin, CreateView):
    """Allows an authenticated user to submit a new article."""

    form_class = NewArticleForm
    model = Article
    template_name = 'authors/create_article.html'

    def get_form(self, form_class=None):
        """Add the appropriate class attributes to the widgets."""
        form = super().get_form(form_class)
        form.fields['title'].widget.attrs.update({"class": "input is-full-width"})
        form.fields['content'].widget.attrs.update({"class": "textarea is-full-width"})
        form.fields['cover_image'].widget.attrs.update({"class": "is-full-width"})
        return form

    def form_valid(self, form):
        """Sets the user as the author."""
        form.instance.author = self.request.user
        form.is_valid()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        """Handle post request including files."""
        form = self.form_class(request.POST, request.FILES)
        if self.form_valid(form):
            form.save()
            return redirect(self.get_success_url())
        else:
            return render(request, self.template_name, {'form': form})

    def get_success_url(self):
        """Gets the success url."""
        return reverse("home:article", kwargs={"pk": self.object.pk, "slug": self.object.slug})


class UpdateArticle(LoginRequiredMixin, UpdateView):
    """Allows an authenticated user to submit a new article."""

    form_class = UpdateArticleForm
    model = Article
    template_name = 'authors/update_article.html'
    context_object_name = "article"

    def get_form(self, form_class=None):
        """Add the appropriate class attributes to the widgets."""
        form = super().get_form(form_class)
        form.fields['title'].widget.attrs.update({"class": "input is-full-width"})
        form.fields['content'].widget.attrs.update({"class": "textarea is-full-width"})
        form.fields['cover_image'].widget.attrs.update({"class": "is-full-width"})
        return form

    def form_valid(self, form):
        """Sets the user as the author."""
        form.is_valid()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        """Handle post request including files."""
        form = self.form_class(request.POST, request.FILES, instance=self.get_object())
        if self.form_valid(form):
            form.save()
            return redirect(self.get_success_url())
        else:
            return render(request, self.template_name, {'form': form})

    def get_success_url(self):
        """Gets the success url."""
        return reverse("home:article", kwargs={"pk": self.object.pk, "slug": self.object.slug})


class DeleteArticle(LoginRequiredMixin, DeleteView):
    """View to delete the article."""

    model = Article
    success_url = reverse_lazy("home:index")
    template_name = 'authors/delete_article.html'
    context_object_name = "article"

website/home/views.py
from django.http import HttpResponse


def index(request):
    """Index dummy view."""
    return HttpResponse("Hello, world. You're at the polls index.")

website/home/views/home.py
"""Views for landing page."""
from django.views.generic import ListView

from ..models import Article


class Home(ListView):
    """The homepage view that displays a list of most recent articles."""

    model = Article
    template_name = "home/home.html"
    context_object_name = 'articles'
    paginate_by = 5

website/home/views/nieuws.py
"""View for a single article."""
from django.views.generic import DetailView

from ..models import Article


class News(DetailView):
    """Detail view for a single news article."""

    model = Article
    template_name = "home/article.html"
    context_object_name = "article"

website/photos/views/article_photos.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, reverse
from django.views.generic import FormView, UpdateView

from website.home.models import Article
from website.photos.forms import MultiplePhotosForm, RemovePhotosFromArticleForm
from website.photos.models import Photo

log = logging.getLogger(__name__)


class ArticlePhotos(LoginRequiredMixin, FormView):
    """A class to create Article Photo views."""

    def get_context_data(self, **kwargs):
        """Get context data for the view."""
        context = super().get_context_data(**kwargs)

        article_pk = self.kwargs["pk"]
        article = get_object_or_404(Article, pk=article_pk)

        context["article"] = article

        return context

    def get_success_url(self):
        """Redirect the user to the article we've added the photos to."""
        article_pk = self.kwargs["pk"]
        article = get_object_or_404(Article, pk=article_pk)
        return reverse("home:article", kwargs={"pk": article.pk, "slug": article.slug})


class ArticleAddPhotos(ArticlePhotos):
    """A view to add photos to an article."""

    form_class = MultiplePhotosForm
    template_name = "photos/article_add_photos.html"

    def post(self, request, *args, **kwargs):
        """Process the form and handle the image files."""
        form = self.get_form()
        if form.is_valid():
            for file in request.FILES.getlist("photos"):
                photo = Photo(image=file, creator=request.user)
                photo.save()
                photo.articles.add(self.kwargs["pk"])
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ArticleRemovePhotos(LoginRequiredMixin, UpdateView):
    """A view that allows a logged-in user to remove photos from an article."""

    model = Article
    form_class = RemovePhotosFromArticleForm
    template_name = "photos/article_remove_photos.html"

    def get_form_kwargs(self):
        """Get the form kwargs for instantiating the form."""
        kwargs = super().get_form_kwargs()
        kwargs["article"] = self.object
        return kwargs

    def form_valid(self, form):
        """Handle a valid form by removing the photos from the article."""
        count = 0
        for photo in form.photos_to_remove:
            self.object.photos.remove(photo)
            count += 1

        verb = "is" if count == 1 else "zijn"
        noun = "foto" if count == 1 else "foto's"

        title = "Foto's verwijderd" if count > 0 else "Geen foto's verwijderd"

        messages.add_message(
            self.request,
            messages.SUCCESS,
            message=f"Er {verb} {count} {noun} verwijderd uit het artikel.",
            extra_tags=title,
        )
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        """Redirect the user to the article the photos were removed from."""
        return reverse("home:article", kwargs={
            "pk": self.object.pk, "slug": self.object.slug
        })

website/userprofile/views/profile.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, reverse
from django.views.generic.edit import UpdateView

from website.userprofile.forms import EditProfileForm
from website.userprofile.models import Profile


class EditProfile(LoginRequiredMixin, UpdateView):
    """Allows an authenticated user to submit a new article."""

    form_class = EditProfileForm
    model = Profile
    template_name = 'userprofile/edit_profile.html'
    context_object_name = "profile"

    def get_object(self, queryset=None):
        """Get the profile for the currently logged-in user."""
        return self.request.user.profile

    def form_valid(self, form):
        """Sets the user as the author."""
        form.is_valid()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        """Handle post request including files."""
        form = self.form_class(request.POST, request.FILES, instance=self.get_object())
        if self.form_valid(form):
            form.save()
            return redirect(self.get_success_url())
        else:
            return render(request, self.template_name, {'form': form})

    def get_success_url(self):
        """Gets the success url."""
        return reverse("home:index")

website/users/views/change_password.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse

from website.users.forms import ChangePasswordForm


class ChangePassword(LoginRequiredMixin, PasswordChangeView):
    """Allow the user to change their password."""

    template_name = "users/change_password.html"
    form_class = ChangePasswordForm

    def get_success_url(self):
        """Get success url with `password changed` message."""
        messages.add_message(
            self.request,
            messages.SUCCESS,
            message="Jouw wachtwoord is gewijzigd.",
            extra_tags='Wachtwoord gewijzigd'
        )
        return reverse("home:index")

website/users/views/login.py
"""Default view for the login page."""
from django.contrib.auth.views import LoginView, LogoutView

from ..forms import AuthForm


class LoginPage(LoginView):
    """The default login view."""

    template_name = "users/login.html"
    form_class = AuthForm


class LogoutPage(LogoutView):
    """The default logout view."""

    form = AuthForm

website/templates/base/base.html
{% load django_simple_bulma %}
{% load sekizai_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="description" content="Website van het Minigigs Cycling Team">
    <meta name="keywords" content="Minigigs Cycling Team, Minigigs, Cycling, Wielrennen, Den Haag">
    <meta name="author" content="Sebastiaan Zeeff">

    <title>Minigigs Cycling Team | {% block title %}Website{% endblock %}</title>

    {% bulma %}

    {# Font-awesome here is defined explicitly so that we can have Pro #}
    <script src="https://kit.fontawesome.com/fe8fdab2df.js"></script>

    <link rel="stylesheet" href="{% static "css/base/base.css" %}">
    {% block head %}{% endblock %}

    {% render_block "css" %}
</head>
<body class="site">
<main class="site-content">
    {% block content %}
        {{ block.super }}
    {% endblock %}
</main>

{% block site_footer %}

<div id="modal-image-popup" class="modal">
    <div class="modal-background"></div>
    <div class="custom-modal-content">
        <div class="box">
            <p class="image">
                <img src="" id="modal-img" alt="Pop-up Image Holder" class="modal-image">
            </p>
        </div>
    </div>
    <button class="modal-close is-large has-background-danger" aria-label="close"></button>
    <button id="gallery-previous" class="button is-primary is-large gallery-button previous-image" aria-label="previous" data-target="modal-image-popup">Vorige</button>
    <button id="gallery-next" class="button is-primary is-large gallery-button next-image" aria-label="next" data-target="modal-image-popup">Volgende</button>
</div>

{% endblock %}
<script src="{% static "js/main.js" %}"></script>
{% render_block "js" %}
</body>
</html>

website/templates/base/messages.html
{% if messages %}
    {% for message in messages %}
        <article class="message is-info">
          <div class="message-header">
              {{ message.extra_tags }}
          </div>
           <div class="message-body">
            {{ message }}
          </div>
        </article>
    {% endfor %}
{% endif %}

website/templates/base/navigation.html
{% load static %}

<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a id="navbar-banner" class="navbar-item" href="/">
            <img src="{% static "images/logos/minigigs_ct_logo.svg" %}" alt="Minigigs Cycling Team logo">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div class="navbar-menu" id="navbar-menu">
        <div class="navbar-end">
            <a class="navbar-item" href="{% url "home:index" %}">
                <span class="icon is-size-5-touch is-medium is-hidden-desktop"><i class="fas fa-newspaper"></i></span>
                <span>Nieuws</span>
            </a>
            {% comment %}
            <a class="navbar-item">
                <span class="icon is-size-5-touch is-medium is-hidden-desktop"><i class="far fa-calendar-alt"></i></span>
                <span>Kalender</span>
            </a>

            <a class="navbar-item">
                <span class="icon is-size-5-touch is-medium is-hidden-desktop"><i class="far fa-envelope"></i></span>
                <span>Contact</span>
            </a>
            {% endcomment %}
            <a class="navbar-item" href="https://www.strava.com/clubs/minigigscyclingteam" target="_blank">
                <span class="icon is-size-4-desktop is-size-5-touch is-medium"><i class="fab fa-strava"></i></span>
                <span>Strava</span>
            </a>
            <a class="navbar-item" href="https://www.youtube.com/channel/UCps6twYjxNuUkEZvRjRewTQ" target="_blank">
                <span class="icon is-size-4-desktop is-size-5-touch is-medium"><i class="fab fa-youtube"></i></span>
                <span>YouTube</span>
            </a>
            {% if user.is_authenticated %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-arrowless">
                        <span class="icon is-size-4-desktop is-size-5-touch is-medium"><i
                                class="fas fa-user"></i></span>
                        <span>{{ user.first_name }}</span>
                    </a>
                    <div class="navbar-dropdown is-right">
                        <a class="navbar-item" href="{% url 'authors:article-new' %}">
                            <span class="icon is-size-6-desktop is-size-6-touch is-medium"><i
                                    class="fas fa-edit"></i></span>
                            <span>Schrijf bericht</span>
                        </a>
                        <a class="navbar-item" href="{% url 'userprofile:profile-edit' %}">
                            <span class="icon is-size-6-desktop is-size-6-touch is-medium"><i
                                    class="fas fa-user"></i></span>
                            <span>Bewerk profiel</span>
                        </a>
                        <a class="navbar-item" href="{% url 'users:change-password' %}">
                            <span class="icon is-size-6-desktop is-size-6-touch is-medium"><i
                                    class="fas fa-user-lock"></i></span>
                            <span>Wijzig wachtwoord</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url "users:logout" %}">
                            <span class="icon is-size-6-desktop is-size-6-touch is-medium"><i
                                    class="fas fa-sign-out-alt"></i></span>
                            <span>Uitloggen</span>
                        </a>
                    </div>
                </div>
            {% else %}
                <a class="navbar-item" href="{% url "users:login" %}">
                    <span class="icon is-size-5-desktop is-size-5-touch is-medium"><i
                            class="fas fa-user-lock"></i></span>
                    <span class="is-hidden-desktop">Inloggen</span>
                </a>
            {% endif %}
        </div>
    </div>
</nav>